使用官方的tomcat镜像

docker run -d --name tomcat-test -p 8888:8080 tomcat:8.5.16-jre8

#      --rm                             Automatically remove the container when it exits
docker run -it --rm -p 8888:8080 tomcat:8.0


docker run -d --name tomcat-test -p 8888:8080 \
-v /home/myWebApp:/usr/local/tomcat/webapps/ROOT \
-v /home/myWebAppLogs:/usr/local/tomcat/logs \
tomcat:8.5.16-jre8




参考
https://www.cnblogs.com/dfengwei/p/7144937.html
https://hub.docker.com/_/tomcat/

